library constants;

import 'package:flutter/material.dart';

const FINISHED_ON_BOARDING = 'finishedOnBoarding';
const COLOR_ACCENT = 0xFF3d8ddb;
const COLOR_PRIMARY_DARK = 0xFF1976D2;
const COLOR_BACKGROUND = 0xff008940;
const COLOR_BACKGROUND_OPPOSITE = 0xFF000000;
const COLOR_PRIMARY = 0xff1976D2;
const COLOR_WHITE = 0xFFffffff;
const COLOR_TEXT_BLACK = 0xFF000000;
const COLOR_TEXT_WHITE = 0xFFFFFFFF;
const COLOR_TEXT_GREY = 0xFFC0C0C0;

const COLOR_BLUE = 0xFF4285F4;
const COLOR_RED = 0xFFEA4335;
const COLOR_YELLOW = 0xFFFBBC05;
const COLOR_GREEN = 0xFF34A853;
const COLOR_YELLO_GREEN = 0xFFBEC100;
const COLOR_YELLO_LEMON = 0xFFfff44f;
const COLOR_TEXT_GREEN = 0xffFF094409;

const ANIMATION_DURATION = 260;

const APP_TITLE = 'Kisan';
const APP_SUBTITLE = 'Kisan App';
const APP_LOGO_PATAH = 'assets/logo.png';
const ASSET_PATAH = 'assets/';
const API_KEY = "";
const currencySymbl = "\₹";
const client_id = "1c714eee-0db2-431a-a941-9b27b2c4d64b";
const client_secret = "61678097-4baa-472c-9fa7-ea628a5d2675";

// mainurl
const apiUrl = "https://id.kisanlab.com";
const send_custom_otp_mobile = apiUrl + "/profiles/send_custom_otp_mobile/";
const api_token_custom_otp_auth = apiUrl + "/api-token-custom-otp-auth/";
const profiles = apiUrl +
    "/profiles/"; //same api can be used for getting user details and updating details
const register = apiUrl + "/register/";
const image_upload = apiUrl + "/image_upload/";
const getadlist = apiUrl + "/administrator/getadlist/";
const products = apiUrl + "/visitor/products";
const companies = apiUrl + "/visitor/companies";
const offers = apiUrl + "/visitor/offers";
const demos = apiUrl + "/visitor/demos";
const launch = apiUrl + "/visitor/launch";
const eventlist = apiUrl + "/samvaad/eventlist/";
const geteventfilters = apiUrl + "/samvaad/geteventfilters/";

List<Map<String, String>> imgSlider = [
  {
    "imgPath": "assets/images/ruralfirst.jpg",
  },
  {
    "imgPayh": "assets/images/tractor2.jpg",
  },
];

List<String> StatesListTitles = [
  "Maharashtra",
  "Karnataka",
  "Andhra Pradesh",
  "Gujarat",
  "Andaman and Nicobar Island (UT)",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh (UT)",
  "Chhattisgarh",
  "Dadra and Nagar Haveli (UT)",
  "Daman and Diu (UT)",
  "Delhi (NCT)",
  "Goa",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Kerala",
  "Lakshadweep (UT)",
  "Madhya Pradesh",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry (UT)",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal"
];

List<String> Maharashtra = [
  "Pune",
  "Ahmednagar",
  "Akola",
  "Amravati",
  "Aurangabad",
  "Beed",
  "Bhandara",
  "Buldhana",
  "Chandrapur",
  "Dhule",
  "Gadchiroli",
  "Gondia",
  "Hingoli",
  "Jalgaon",
  "Jalna",
  "Kolhapur",
  "Latur",
  "Mumbai City",
  "Mumbai Suburban",
  "Nagpur",
  "Nanded",
  "Nandurbar",
  "Nashik",
  "Osmanabad",
  "Parbhani",
  "Palghar",
  "Raigad",
  "Ratnagiri",
  "Sangli",
  "Satara",
  "Sindhudurg",
  "Solapur",
  "Thane",
  "Wardha",
  "Washim",
  "Yavatmal",
];

List<String> Karnataka = [
  "Bagalkot",
  "Bengaluru (Bangalore) Rural",
  "Bengaluru (Bangalore) Urban",
  "Belagavi (Belgaum)",
  "Ballari (Bellary)",
  "Bidar",
  "Chamarajanagar",
  "Chikkamagaluru (Chikmagalur)",
  "Chikballapur",
  "Chitradurga",
  "Dakshina Kannada",
  "Davangere",
  "Dharwad",
  "Gadag",
  "Kalaburagi (Gulbarga)",
  "Hassan",
  "Haveri",
  "Kodagu",
  "Kolar",
  "Koppal",
  "Mandya",
  "Mysuru (Mysore)",
  "Raichur",
  "Ramanagara",
  "Shivamogga (Shimoga)",
  "Tumakuru (Tumkur)",
  "Udupi",
  "Uttara Kannada (Karwar)",
  "Vijayapura (Bijapur)",
  "Yadgir",
];
List<String> Andhra_Pradesh = [
  "Anantapur",
  "Chittoor",
  "YSR District, Kadapa (Cuddapah)",
  "East Godavari",
  "Guntur",
  "Krishna",
  "Kurnool",
  "Sri Potti Sriramulu Nellore",
  "Prakasam",
  "Srikakulam",
  "Visakhapatnam",
  "Vizianagaram",
  "West Godavari",
];

List<String> Gujarat = [
  "Ahmedabad",
  "Amreli",
  "Anand",
  "Aravalli",
  "Banaskantha (Palanpur)",
  "Bharuch",
  "Bhavnagar",
  "Botad",
  "Chhota Udepur",
  "Dahod",
  "Dangs (Ahwa)",
  "Devbhoomi Dwarka",
  "Gandhinagar",
  "Gir Somnath",
  "Jamnagar",
  "Junagadh",
  "Kachchh",
  "Kheda",
  "Mahisagar",
  "Mehsana",
  "Morbi",
  "Narmada (Rajpipla)",
  "Navsari",
  "Panchmahal (Godhra)",
  "Patan",
  "Porbandar",
  "Rajkot",
  "Sabarkantha (Himmatnagar)",
  "Surat",
  "Surendranagar",
  "Tapi (Vyara)",
  "Vadodara",
  "Valsad",
];

List<String> Andaman_and_Nicobar = [
  "Nicobar",
  "North and Middle Andaman",
  "South Andaman",
];

List<String> ArunachalPradesh = [
  "Anjaw",
  "Changlang",
  "Dibang Valley",
  "East Kameng",
  "East Siang",
  "Kamle",
  "Kra Daadi",
  "Kurung Kumey",
  "Lepa Rada",
  "Lower Siang",
  "Lohit",
  "Longding",
  "Lower Dibang Valley",
  "Lower Siang",
  "Lower Subansiri",
  "Namsai",
  "Pakke Kessang",
  "Papum Pare",
  "Shi Yomi",
  "Siang",
  "Tawang",
  "Tirap",
  "Upper Siang",
  "Upper Subansiri",
  "West Kameng",
  "West Siang",
];

List<String> Assam = [
  "Barpeta",
  "Baksa",
  "Biswanath",
  "Bongaigaon",
  "Cachar",
  "Charaideo",
  "Chirang",
  "Darrang",
  "Dhemaji",
  "Dhubri",
  "Dibrugarh",
  "Dima Hasao (North Cachar Hills)",
  "Goalpara",
  "Golaghat",
  "Hailakandi",
  "Hojai",
  "Jorhat",
  "Kamrup",
  "Kamrup Metropolitan",
  "Karbi Anglong",
  "Karimganj",
  "Kokrajhar",
  "Lakhimpur",
  "Majuli",
  "Morigaon",
  "Nagaon",
  "Nalbari",
  "Sivasagar",
  "Sonitpur",
  "South Salamara-Mankachar",
  "Tinsukia",
  "Udalguri",
  "West Karbi Anglong",
];

List<String> Bihar = [
  "Araria",
  "Arwal",
  "Aurangabad",
  "Banka",
  "Begusarai",
  "Bhagalpur",
  "Bhojpur",
  "Buxar",
  "Darbhanga",
  "East Champaran (Motihari)",
  "Gaya",
  "Gopalganj",
  "Jamui",
  "Jehanabad",
  "Kaimur (Bhabua)",
  "Katihar",
  "Khagaria",
  "Kishanganj",
  "Lakhisarai",
  "Madhepura",
  "Madhubani",
  "Munger (Monghyr)",
  "Muzaffarpur",
  "Nalanda",
  "Nawada",
  "Patna",
  "Purnia (Purnea)",
  "Rohtas",
  "Saharsa",
  "Samastipur",
  "Saran",
  "Sheikhpura",
  "Sheohar",
  "Sitamarhi",
  "Siwan",
  "Supaul",
  "Vaishali",
  "West Champaran",
];

List<String> Chandigarh = ["Chandigarh"];

List<String> Chhattisgarh = [
  "Balod",
  "Baloda Bazar",
  "Balrampur",
  "Bastar",
  "Bemetara",
  "Bijapur",
  "Bilaspur",
  "Dantewada ( South Bastar)",
  "Dhamtari",
  "Durg",
  "Gariyaband",
  "Janjgir-Champa",
  "Jashpur",
  "Kabirdham (Kawardha)",
  "Kanker (North Bastar)",
  "Kondagaon",
  "Korba",
  "Korea (Koriya)",
  "Mahasamund",
  "Mungeli",
  "Narayanpur",
  "Raigarh",
  "Raipur",
  "Rajnandgaon",
  "Sukma",
  "Surajpur",
  "Surguja",
];

List<String> DadarandNagarHaveli = [
  "Select District",
  "Dadra and Nagar Haveli (UT)",
];

List<String> DamanandDiu = [
  "Select District",
  "Daman",
  "Diu",
];
List<String> Delhi = [
  "Select District",
  "Central Delhi",
  "East Delhi",
  "New Delhi",
  "North Delhi",
  "North East Delhi",
  "North West Delhi",
  "Shahdara",
  "South Delhi",
  "South East Delhi",
  "South West Delhi",
  "West Delhi",
];

List<String> Goa = [
  "Select District",
  "North Goa",
  "South Goa",
];
List<String> Haryana = [
  "Select District",
  "Ambala",
  "Bhiwani",
  "Charkhi Dadri",
  "Faridabad",
  "Fatehabad",
  "Gurugram (Gurgaon)",
  "Hisar",
  "Jhajjar",
  "Jind",
  "Kaithal",
  "Karnal",
  "Kurukshetra",
  "Mahendragarh",
  "Nuh",
  "Palwal",
  "Panchkula",
  "Panipat",
  "Rewari",
  "Rohtak",
  "Sirsa",
  "Sonipat",
  "Yamunanagar",
];
List<String> HimachalPradesh = [
  "Select District",
  "Bilaspur",
  "Chamba",
  "Hamirpur",
  "Kangra",
  "Kinnaur",
  "Kullu",
  "Lahaul &amp; Spiti",
  "Mandi",
  "Shimla",
  "Sirmaur (Sirmour)",
  "Solan",
  "Una",
];
List<String> JammuandKashmir = [
  "Select District",
  "Anantnag",
  "Bandipore",
  "Baramulla",
  "Budgam",
  "Doda",
  "Ganderbal",
  "Jammu",
  "Kargil",
  "Kathua",
  "Kishtwar",
  "Kulgam",
  "Kupwara",
  "Leh",
  "Poonch",
  "Pulwama",
  "Rajouri",
  "Ramban",
  "Reasi",
  "Samba",
  "Shopian",
  "Srinagar",
  "Udhampur",
];

List<String> Jharkhand = [
  "Select District",
  "Bokaro",
  "Chatra",
  "Deoghar",
  "Dhanbad",
  "Dumka",
  "East Singhbhum",
  "Garhwa",
  "Giridih",
  "Godda",
  "Gumla",
  "Hazaribag",
  "Jamtara",
  "Khunti",
  "Koderma",
  "Latehar",
  "Lohardaga",
  "Pakur",
  "Palamu",
  "Ramgarh",
  "Ranchi",
  "Sahibganj",
  "Seraikela-Kharsawan",
  "Simdega",
  "West Singhbhum",
];

List<String> Kerala = [
  "Select District",
  "Alappuzha",
  "Ernakulam",
  "Idukki",
  "Kannur",
  "Kasaragod",
  "Kollam",
  "Kottayam",
  "Kozhikode",
  "Malappuram",
  "Palakkad",
  "Pathanamthitta",
  "Thiruvananthapuram",
  "Thrissur",
  "Wayanad",
];

List<String> Lakshadweep = [
  "Select District",
  "Lakshadweep",
];
List<String> MadhyaPradesh = [
  "Select District",
  "Agar Malwa",
  "Alirajpur",
  "Anuppur",
  "Ashoknagar",
  "Balaghat",
  "Barwani",
  "Betul",
  "Bhind",
  "Bhopal",
  "Burhanpur",
  "Chhatarpur",
  "Chhindwara",
  "Damoh",
  "Datia",
  "Dewas",
  "Dhar",
  "Dindori",
  "Guna",
  "Gwalior",
  "Harda",
  "Hoshangabad",
  "Indore",
  "Jabalpur",
  "Jhabua",
  "Katni",
  "Khandwa",
  "Khargone",
  "Mandla",
  "Mandsaur",
  "Morena",
  "Narsinghpur",
  "Neemuch",
  "Panna",
  "Raisen",
  "Rajgarh",
  "Ratlam",
  "Rewa",
  "Sagar",
  "Satna",
  "Sehore",
  "Seoni",
  "Shahdol",
  "Shajapur",
  "Sheopur",
  "Shivpuri",
  "Sidhi",
  "Singrauli",
  "Tikamgarh",
  "Ujjain",
  "Umaria",
  "Vidisha",
];

List<String> Manipur = [
  "Select District",
  "Bishnupur",
  "Chandel",
  "Churachandpur",
  "Imphal East",
  "Imphal West",
  "Jiribam",
  "Kakching",
  "Kamjong",
  "Kangpokpi",
  "Noney",
  "Pherzawl",
  "Senapati",
  "Tamenglong",
  "Tengnoupal",
  "Thoubal",
  "Ukhrul",
];
List<String> Meghalaya = [
  "Select District",
  "East Garo Hills",
  "East Jaintia Hills",
  "East Khasi Hills",
  "North Garo Hills",
  "Ri Bhoi",
  "South Garo Hills",
  "South West Garo Hills",
  "South West Khasi Hills",
  "West Garo Hills",
  "West Jaintia Hills",
  "West Khasi Hills",
];
List<String> Mizoram = [
  "Select District",
  "Aizawl",
  "Champhai",
  "Kolasib",
  "Lawngtlai",
  "Lunglei",
  "Mamit",
  "Saiha",
  "Serchhip",
];
List<String> Nagaland = [
  "Select District",
  "Dimapur",
  "Kiphire",
  "Kohima",
  "Longleng",
  "Mokokchung",
  "Mon",
  "Peren",
  "Phek",
  "Tuensang",
  "Wokha",
  "Zunheboto",
];
List<String> Odisha = [
  "Select District",
  "Angul",
  "Balangir",
  "Balasore",
  "Bargarh",
  "Bhadrak",
  "Boudh",
  "Cuttack",
  "Deogarh",
  "Dhenkanal",
  "Gajapati",
  "Ganjam",
  "Jagatsinghapur",
  "Jajpur",
  "Jharsuguda",
  "Kalahandi",
  "Kandhamal",
  "Kendrapara",
  "Kendujhar (Keonjhar)",
  "Khordha",
  "Koraput",
  "Malkangiri",
  "Mayurbhanj",
  "Nabarangpur",
  "Nayagarh",
  "Nuapada",
  "Puri",
  "Rayagada",
  "Sambalpur",
  "Sonepur",
  "Sundargarh",
];

List<String> Puducherry = [
  "Select District",
  "Karaikal",
  "Mahe",
  "Puducherry",
  "Yanam",
];
List<String> Punjab = [
  "Select District",
  "Amritsar",
  "Barnala",
  "Bathinda",
  "Faridkot",
  "Fatehgarh Sahib",
  "Fazilka",
  "Firozpur",
  "Gurdaspur",
  "Hoshiarpur",
  "Jalandhar",
  "Kapurthala",
  "Ludhiana",
  "Mansa",
  "Moga",
  "Muktsar",
  "Nawanshahr (Shahid Bhagat Singh Nagar)",
  "Pathankot",
  "Patiala",
  "Rupnagar",
  "Sangrur",
  "Sahibzada Ajit Singh Nagar (Mohali)",
  "Tarn Taran",
];
List<String> Rajasthan = [
  "Select District",
  "Ajmer",
  "Alwar",
  "Banswara",
  "Baran",
  "Barmer",
  "Bharatpur",
  "Bhilwara",
  "Bikaner",
  "Bundi",
  "Chittorgarh",
  "Churu",
  "Dausa",
  "Dholpur",
  "Dungarpur",
  "Hanumangarh",
  "Jaipur",
  "Jaisalmer",
  "Jalore",
  "Jhalawar",
  "Jhunjhunu",
  "Jodhpur",
  "Karauli",
  "Kota",
  "Nagaur",
  "Pali",
  "Pratapgarh",
  "Rajsamand",
  "Sawai Madhopur",
  "Sikar",
  "Sirohi",
  "Sri Ganganagar",
  "Tonk",
  "Udaipur",
];
List<String> Sikkim = [
  "Select District",
  "East Sikkim",
  "North Sikkim",
  "South Sikkim",
  "West Sikkim",
];

List<String> TamilNadu = [
  "Select District",
  "Ariyalur",
  "Chengalpattu",
  "Chennai",
  "Coimbatore",
  "Cuddalore",
  "Dharmapuri",
  "Dindigul",
  "Erode",
  "Kallakurichi",
  "Kanchipuram",
  "Kanyakumari",
  "Karur",
  "Krishnagiri",
  "Madurai",
  "Nagapattinam",
  "Namakkal",
  "Nilgiris",
  "Perambalur",
  "Pudukkottai",
  "Ramanathapuram",
  "Ranipet",
  "Salem",
  "Sivaganga",
  "Tenkasi",
  "Thanjavur",
  "Theni",
  "Thoothukudi (Tuticorin)",
  "Tiruchirappalli",
  "Tirunelveli",
  "Tirupathur",
  "Tiruppur",
  "Tiruvallur",
  "Tiruvannamalai",
  "Tiruvarur",
  "Vellore",
  "Viluppuram",
  "Virudhunagar",
];

List<String> Telangana = [
  "Select District",
  "Adilabad",
  "Bhadradri Kothagudem",
  "Hyderabad",
  "Jagtial",
  "Jangaon",
  "Jayashankar Bhoopalpally",
  "Jogulamba Gadwal",
  "Kamareddy",
  "Karimnagar",
  "Khammam",
  "Komaram Bheem Asifabad",
  "Mahabubabad",
  "Mahabubnagar",
  "Mancherial",
  "Medak",
  "Medchal",
  "Nagarkurnool",
  "Nalgonda",
  "Nirmal",
  "Nizamabad",
  "Peddapalli",
  "Rajanna Sircilla",
  "Rangareddy",
  "Sangareddy",
  "Siddipet",
  "Suryapet",
  "Vikarabad",
  "Wanaparthy",
  "Warangal (Rural)",
  "Warangal (Urban)",
  "Yadadri Bhuvanagiri",
];

List<String> Tripura = [
  "Select District",
  "Dhalai",
  "Gomati",
  "North Tripura",
  "Sepahijala",
  "South Tripura",
  "Unakoti",
  "West Tripura",
];

List<String> UttarPradesh = [
  "Select District",
  "Agra",
  "Aligarh",
  "Allahabad",
  "Ambedkar Nagar",
  "Amethi (Chatrapati Sahuji Mahraj Nagar)",
  "Amroha (J.P. Nagar)",
  "Auraiya",
  "Azamgarh",
  "Baghpat",
  "Bahraich",
  "Ballia",
  "Balrampur",
  "Banda",
  "Barabanki",
  "Bareilly",
  "Basti",
  "Bijnor",
  "Budaun",
  "Bulandshahr",
  "Chandauli",
  "Chitrakoot",
  "Deoria",
  "Etah",
  "Etawah",
  "Faizabad",
  "Farrukhabad",
  "Fatehpur",
  "Firozabad",
  "Gautam Buddha Nagar",
  "Ghaziabad",
  "Ghazipur",
  "Gonda",
  "Gorakhpur",
  "Hamirpur",
  "Hapur (Panchsheel Nagar)",
  "Hardoi",
  "Hathras",
  "Jalaun",
  "Jaunpur",
  "Jhansi",
  "Kannauj",
  "Kanpur Dehat",
  "Kanpur Nagar",
  "Kanshiram Nagar (Kasganj)",
  "Kaushambi",
  "Kushinagar (Padrauna)",
  "Lakhimpur - Kheri",
  "Lalitpur",
  "Lucknow",
  "Maharajganj",
  "Mahoba",
  "Mainpuri",
  "Mathura",
  "Mau",
  "Meerut",
  "Mirzapur",
  "Moradabad",
  "Muzaffarnagar",
  "Pilibhit",
  "Pratapgarh",
  "RaeBareli",
  "Rampur",
  "Saharanpur",
  "Sambhal (Bhim Nagar)",
  "Sant Kabir Nagar",
  "Bhadohi",
  "Shahjahanpur",
  "Shamali (Prabuddh Nagar)",
  "Shravasti",
  "Siddharth Nagar",
  "Sitapur",
  "Sonbhadra",
  "Sultanpur",
  "Unnao",
  "Varanasi",
];

List<String> Uttarakhand = [
  "Select District",
  "Almora",
  "Bageshwar",
  "Chamoli",
  "Champawat",
  "Dehradun",
  "Haridwar",
  "Nainital",
  "Pauri Garhwal",
  "Pithoragarh",
  "Rudraprayag",
  "Tehri Garhwal",
  "Udham Singh Nagar",
  "Uttarkashi",
];

List<String> WestBengal = [
  "Select District",
  "Alipurduar",
  "Bankura",
  "Birbhum",
  "Paschim (West) Burdwan (Bardhaman)",
  "Purba Burdwan (Bardhaman)",
  "Cooch Behar",
  "Dakshin Dinajpur ( South Dinajpur)",
  "Darjeeling",
  "Hooghly",
  "Howrah",
  "Jalpaiguri",
  "Jhargram",
  "Kalimpong",
  "Kolkata",
  "Malda",
  "Murshidabad",
  "Nadia",
  "North 24 Parganas",
  "Paschim Medinipur (West Medinipur)",
  "Purba Medinipur (East Medinipur)",
  "Purulia",
  "South 24 Parganas",
  "Uttar Dinajpur (North Dinajpur)",
];

List<List<String>> distList = [
  Maharashtra,
  Karnataka,
  Andhra_Pradesh,
  Gujarat,
  Andaman_and_Nicobar,
  ArunachalPradesh,
  Assam,
  Bihar,
  Chandigarh,
  Chhattisgarh,
  DadarandNagarHaveli,
  DamanandDiu,
  Delhi,
  Goa,
  Haryana,
  HimachalPradesh,
  JammuandKashmir,
  Jharkhand,
  Kerala,
  Lakshadweep,
  MadhyaPradesh,
  Manipur,
  Meghalaya,
  Mizoram,
  Nagaland,
  Odisha,
  Puducherry,
  Punjab,
  Rajasthan,
  Sikkim,
  TamilNadu,
  Telangana,
  Tripura,
  UttarPradesh,
  Uttarakhand,
  WestBengal
];
