class EventListParser {
  int user_id, duration, audience_size, featured;

  String title,
      about,
      scheduled_date,
      scheduled_time,
      language,
      website,
      image_path,
      status,
      share_link,
      featured_note,
      image_path_medium,
      image_path_small,
      price,
      about_hindi,
      about_marathi,
      media_url,
      pavilion_id,
      eventcode,
      image_bigthumb_url,
      image_smallthumb_url,
      organisation_name,
      first_name,
      last_name,
      mobile;

  bool nature, is_paid;

  EventListParser(
      {this.user_id,
      this.title,
      this.about,
      this.scheduled_date,
      this.scheduled_time,
      this.duration,
      this.language,
      this.website,
      this.image_path,
      this.status,
      this.nature,
      this.share_link,
      this.audience_size,
      this.featured,
      this.featured_note,
      this.image_path_medium,
      this.image_path_small,
      this.price,
      this.about_hindi,
      this.about_marathi,
      this.media_url,
      this.is_paid,
      this.pavilion_id,
      this.eventcode,
      this.image_bigthumb_url,
      this.image_smallthumb_url,
      this.organisation_name,
      this.first_name,
      this.last_name,
      this.mobile});

  factory EventListParser.fromJson(Map<String, dynamic> json) =>
      EventListParser(
        user_id: json["user_id"],
        title: json["title"],
        about: json["about"],
        scheduled_date: json["scheduled_date"],
        scheduled_time: json["scheduled_time"],
        duration: json["duration"],
        language: json["language"],
        website: json["website"],
        image_path: json["image_path"],
        status: json["status"],
        nature: json["nature"],
        share_link: json["share_link"],
        audience_size: json["audience_size"],
        featured: json["featured"],
        featured_note: json["featured_note"],
        image_path_medium: json["image_path_medium"],
        image_path_small: json["image_path_small"],
        price: json["price"],
        about_hindi: json["about_hindi"],
        about_marathi: json["about_marathi"],
        media_url: json["media_url"],
        is_paid: json["is_paid"],
        pavilion_id: json["pavilion_id"],
        eventcode: json["eventcode"],
        image_bigthumb_url: json["image_bigthumb_url"],
        image_smallthumb_url: json["image_smallthumb_url"],
        organisation_name: json["organisation_name"],
        first_name: json["first_name"],
        last_name: json["last_name"],
        mobile: json["mobile"],
      );
}
