class OfferListParser {
  int offer_id, for_item_id, offer_type;
  double random, amount, price;
  String media_id,
      title,
      description,
      percentage_discount,
      currency,
      disclaimer,
      title_marathi,
      title_hindi,
      desc_marathi,
      desc_hindi,
      title_english,
      desc_english,
      organisation_name,
      media_url,
      bigthumb_url,
      smallthumb_url,
      media_type;

  bool featured;

  OfferListParser(
      {this.offer_id,
      this.random,
      this.media_id,
      this.for_item_id,
      this.title,
      this.description,
      this.offer_type,
      this.amount,
      this.percentage_discount,
      this.currency,
      this.disclaimer,
      this.title_marathi,
      this.title_hindi,
      this.desc_marathi,
      this.desc_hindi,
      this.title_english,
      this.desc_english,
      this.price,
      this.featured,
      this.organisation_name,
      this.media_url,
      this.bigthumb_url,
      this.smallthumb_url,
      this.media_type});

  factory OfferListParser.fromJson(Map<String, dynamic> json) =>
      OfferListParser(
          offer_id: json["offer_id"],
          random: json["random"],
          media_id: json["media_id"],
          for_item_id: json["for_item_id"],
          title: json["title"],
          description: json["description"],
          offer_type: json["offer_type"],
          amount: json["amount"],
          percentage_discount: json["percentage_discount"],
          currency: json["currency"],
          disclaimer: json["disclaimer"],
          title_marathi: json["title_marathi"],
          title_hindi: json["title_hindi"],
          desc_marathi: json["desc_marathi"],
          desc_hindi: json["desc_hindi"],
          title_english: json["title_english"],
          price: json["price"],
          featured: json["featured"],
          organisation_name: json["organisation_name"],
          media_url: json["media_url"],
          bigthumb_url: json["bigthumb_url"],
          smallthumb_url: json["smallthumb_url"],
          media_type: json["media_type"]);
}
