class UserProfileParser {
  String about,
      address1,
      address2,
      address3,
      city,
      state,
      pin,
      country,
      mobile1,
      email,
      longitude,
      latitude,
      designation,
      occupation,
      occupation_other,
      gender,
      avatar,
      image_url,
      image_bigthumb_url,
      image_smallthumb_url,
      registration_type,
      sso_id,
      tehsil;

  int account_type, user;

  bool has_paid,
      is_email_verified,
      is_mobile_verified,
      is_dnd,
      whatsapp_opt_in_status;

  UserProfileParser(
      this.about,
      this.account_type,
      this.address1,
      this.address2,
      this.address3,
      this.city,
      this.state,
      this.pin,
      this.country,
      this.mobile1,
      this.email,
      this.has_paid,
      this.longitude,
      this.latitude,
      this.designation,
      this.occupation,
      this.occupation_other,
      this.gender,
      this.avatar,
      this.image_url,
      this.image_bigthumb_url,
      this.image_smallthumb_url,
      this.registration_type,
      this.is_email_verified,
      this.is_mobile_verified,
      this.sso_id,
      this.tehsil,
      this.is_dnd,
      this.whatsapp_opt_in_status,
      this.user);

}
